### PR TITLE
redundancy fix in get_index, test added

### LINKED ISSUE #133: [TASK] Eliminate redundancy in Merkle tree get_index method
In our `get_index` method ([here](https://github.com/webb-tools/arkworks-gadgets/blob/9a9fb34ed56fde4136b7159c308a921e3c55a7b5/arkworks-gadgets/src/merkle_tree/constraints.rs#L192-L222)) for computing the index of a leaf in a Merkle tree we have some redundancy.  The method starts with by calling `check_membership` to generate a proof that the `leaf` does indeed belong to a tree with the given `root_hash`.  The way `check_membership` works is to start at the leaf-level of a path and work its way up to the root, computing the hash of the siblings at each level and checking that this matches one of the siblings at the level above.  It adds all these computations to the constraint system.

All this work is then repeated by `get_index` as it hashes up the path to properly determine the index of `leaf`.  So a lot of this hashing is proven twice.  

One way to eliminate it would be to simply eliminate the membership check at the beginning and then add a few lines at the end to confirm that the siblings at the final level of this path do indeed hash to `root_hash`.  In fact these siblings are already being hashed together in the final step of the for-loop (further redundancy, since the result `previous_hash` is never used after exiting the for loop), so all we need to do is add 

```rust
let isonpath = previous_hash.is_eq(root);
isonpath.unwrap().enforce_equal(&Boolean::TRUE)?;
```

after the for loop, prior to return.

All this applies as well for the [plonk version](https://github.com/webb-tools/arkworks-gadgets/blob/8de3679d02693cbc94cecdbb395a137bc22ee86d/arkworks-plonk-circuits/src/merkle_tree/mod.rs#L84-L122) with appropriate modifications.

### PR DESCRIPTION
**Pull request by GhostOfGauss**
This is to close #133 .  The unnecessary call to `check_membership` has been removed from `get_index` and the validity of the path is still checked.  The number of constraints is cut in half by this change (from about 22k to about 11k).  A test is added to make sure that `get_index` will indeed still reject invalid paths.

### CODE REVIEW

File: arkworks-gadgets/src/merkle_tree/constraints.rs [hunk 1]
```diff
@@ -222,6 +218,10 @@ where
 			)?;
 		}
 
+		// Now check that path has the correct Merkle root
+		let isonpath = previous_hash.is_eq(root);
```
Comment (drewstone) [inline arkworks-gadgets/src/merkle_tree/constraints.rs:222]: Can we use snake casing for this? is_on_path

**Review by drewstone — CHANGES_REQUESTED** [review]
Looks good! Just a stylistic fix needed.

File: arkworks-gadgets/src/merkle_tree/constraints.rs (hunk 1 above)
Comment (GhostOfGauss) [reply arkworks-gadgets/src/merkle_tree/constraints.rs]: for sure, all done
